=== zhoumary/nodejs-training/training.config.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/NodeTrainingConfiguration",
    "definitions": {
        "NodeTrainingConfiguration": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "author": {
                    "type": "string",
                    "description": "author name"
                },
                "specs": {
                    "type": "string",
                    "description": "spec url for downloading/uploading"
                },
                "callback": {
                    "type": "string",
                    "description": "test result callback"
                },
                "role": {
                    "type": "string",
                    "description": "user role",
                    "enum": [
                        "trainee",
                        "trainer"
                    ]
                },
                "credential": {
                    "$ref": "#/definitions/Credential"
                }
            },
            "required": [
                "author",
                "role"
            ],
            "title": "NodeTrainingConfiguration"
        },
        "Credential": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "required": [
                "password",
                "username"
            ],
            "title": "Credential"
        }
    }
}

=== zhoumary/nodejs-training/training.config.json
{
    "author": "Fiona Zhou",
    "specs": "https://couchdb.eu-central.fornever.org/training_spec/cim-training",
    "callback": "https://couchdb.eu-central.fornever.org/training_result",
    "role": "trainee",
    "credential": {
        "username": "training",
        "password": "training"
    }
}
